[package]
name = "syscall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
numeric-enum-macro = "0.2.0"
bitflags = "1.3.2"

[features]
default = ["riscv"]
riscv = []