[package]
name = "Mstd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core2 = { version = "0.4.0", default-features = false, features = ["alloc", "nightly"] }
spin = "0.9.2"
bitflags = "1.3.2"
talc = "4"
embedded-graphics = { version = "0.8", optional = true }
pconst = { git = "https://github.com/os-module/pconst.git" }

[features]
gui = ["embedded-graphics"]

