[package]
name = "syscall-table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.2"
systable-macro-derive = {path = "../systable-macro-derive"}



[features]
default = ["alloc"]
std = []
alloc =[]